monitor:
  check_file_enabled: true
  check_file_path: /app/monitor_targets/test.txt
  check_gpu_power_consecutive_checks: 3
  check_gpu_power_enabled: false
  check_gpu_power_gpu_ids: all
  check_gpu_power_threshold: 50.0
  check_interval: 5
  check_log_enabled: false
  check_log_markers:
  - Training completed
  - ä»»åŠ¡å®Œæˆ
  - è®­ç»ƒå®Œæˆ
  - Epoch [300/300]
  check_log_mode: incremental
  check_log_path: /app/monitor_targets/test.log
  logprint: 60
  project_name: ç›‘æ§ä»»åŠ¡
  timeout: null
webhook:
  color: green
  enabled: true
  footer: æ­¤æ¶ˆæ¯ç”±TaskNyaå‘é€
  include_duration: true
  include_duration_title: æ€»è€—æ—¶æµ‹è¯•
  include_end_time: true
  include_end_time_title: ä»»åŠ¡ç»“æŸæ—¶é—´
  include_gpu_info: true
  include_gpu_info_title: GPUä¿¡æ¯
  include_hostname: true
  include_hostname_title: ä¸»æœºå
  include_method: true
  include_method_title: ç³»ç»Ÿåˆ¤æ–­ä¾æ®
  include_project_name: true
  include_project_name_title: ç›‘æ§ä»»åŠ¡
  include_start_time: true
  include_start_time_title: ä»»åŠ¡å¼€å§‹
  title: ğŸ‰ ç›‘æ§ä»»åŠ¡å®Œæˆé€šçŸ¥
  url: https://open.feishu.cn/open-apis/bot/v2/hook/yoururl
