monitor:
  check_file_enabled: true
  check_file_path: D:\User\Downloads\b站抽奖动态_恋爱0公里_20260111\b站抽奖动态\text.txt
  check_gpu_power_consecutive_checks: 3
  check_gpu_power_enabled: false
  check_gpu_power_gpu_ids: all
  check_gpu_power_threshold: 20
  check_interval: 1
  check_log_enabled: false
  check_log_markers:
  - 完成
  - done
  check_log_mode: full
  check_log_path: /tmp/test.log
  logprint: 5
  project_name: 单元测试任务
  timeout: 0
webhook:
  color: green
  enabled: true
  footer: 测试消息
  include_duration: true
  include_duration_title: 耗时
  include_end_time: true
  include_end_time_title: 结束
  include_gpu_info: false
  include_gpu_info_title: GPU
  include_hostname: true
  include_hostname_title: 主机
  include_method: true
  include_method_title: 方式
  include_project_name: true
  include_project_name_title: 项目
  include_start_time: true
  include_start_time_title: 开始
  title: 测试通知
  url: https://open.feishu.cn/open-apis/bot/v2/hook/dad04f75-770a-4c27-a89b-5ce8bdeb8825
