generic_webhook:
  anime_quote_enabled: true
  body: "{\n  \"content\": \"[ ${project_name} ]\\n----------------------------\\\
    n触发方式: ${method}\\n触发详情: ${detail}\\n----------------------------\\n[ 数据统计 ]\\\
    n报告统计: ${report_summary}\\n变更列表: ${report_change_list}\\n提示: ${report_actions}\\\
    n----------------------------\\n详情查看: https://xxxx.xxxx.xxxx:xxxx\\\
    n\\n${anime_quote}\\n[ 来自 XiaoXue-TaskNya 推送 ]\",\n  \"umo\": \"飘雪:GroupMessage:xxxxxxxx\"\
    ,\n  \"message_type\": \"text\"\n}"
  enabled: true
  headers:
    Authorization: Bearer xxxxxxxx
    Content-Type: application/json
  method: POST
  retry_count: 2
  timeout: 10
  url: http://xxxx.xxx.xxxx:10010/send
monitor:
  check_directory_action_keywords: 
    准备压制视频了哦(๑•̀ㅂ•́)ﻭ✧:
    - 无字幕
    压制视频已上传:
    - x264
    字幕准备就绪ヾ(≧▽≦*)o:
    - 已校
    视频工程文件已上传(◦˙▽˙◦):
    - 已复制
    视频组件已上传o((^▽^))o:
    - 片头
    - 片尾
    请注意校对字幕(✿◡‿◡):
    - 未校
    音频缩混已上传(๑˃̵ᴗ˂̵)ﻭ:
    - 缩混
  check_directory_continuous_mode: true
  check_directory_detect_added: true
  check_directory_detect_modified: false
  check_directory_detect_removed: false
  check_directory_enabled: true
  check_directory_exclude_keywords: 
  - 年报
  - 测试用素材
  - 往期周报
  - 视频模板
  check_directory_include_folders: false
  check_directory_path: D:\User\Downloads\
  check_directory_recheck_delay: 20
  check_directory_report_path: ''
  check_file_detect_deletion: false
  check_file_enabled: false
  check_file_path: /tmp/test_file.txt
  check_file_recheck_delay: 0
  check_gpu_power_consecutive_checks: 3
  check_gpu_power_enabled: false
  check_gpu_power_gpu_ids: all
  check_gpu_power_threshold: 50.0
  check_gpu_power_trigger_mode: below
  check_interval: 60
  check_log_enabled: false
  check_log_markers:
  - 完成
  - done
  check_log_mode: full
  check_log_path: /tmp/test.log
  logprint: 60
  project_name: 监控任务
  timeout: 0
webhook:
  color: green
  enabled: false
  footer: 测试消息
  include_duration: true
  include_duration_title: 耗时
  include_end_time: true
  include_end_time_title: 结束
  include_gpu_info: false
  include_gpu_info_title: GPU
  include_hostname: true
  include_hostname_title: 主机
  include_method: true
  include_method_title: 方式
  include_project_name: true
  include_project_name_title: 项目
  include_start_time: true
  include_start_time_title: 开始
  title: 测试通知
  url: https://test.webhook.url/hook
